name: Cleaning

on:
  workflow_dispatch:
    inputs:
      Clean_Release:
        description: "Cleanup Old Releases"
        required: false
        default: true
        type: boolean
      Clean_Artifacts:
        description: "Cleanup Old Artifacts"
        required: false
        default: true
        type: boolean
      Clean_Workflow_Logs:
        description: "Cleanup Workflow Logs"
        required: false
        default: true
        type: boolean

jobs:
  Cleanup-Old-Releases:
    runs-on: ubuntu-20.04
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
    - name: Delete Older Releases
      uses: dev-drprasad/delete-older-releases@master
      if: inputs.Clean_Release == 'true'
      with:
        keep_latest: 9
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  Cleanup-Old-Artifacts:
    runs-on: ubuntu-20.04
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
    - name: Cleanup Old Action Artifacts
      uses: heidi-pay/gha-delete-artifacts@main
      if: inputs.Clean_Artifacts == 'true'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        days: 3
        max-artifacts-to-delete: 100
        dry-run: no

  Cleanup-Workflow-Logs:
    runs-on: ubuntu-20.04
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Cleanup Workflow Logs
        uses: Mattraks/delete-workflow-runs@main
        if: inputs.Clean_Workflow_Logs == 'true'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 3
