name: Cleaning

on:
  workflow_dispatch:

jobs:
  Cleanup-workflow runs:
    runs-on: ubuntu-20.04
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Cleanup workflow runs
        uses: dmvict/clean-workflow-runs@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          save_period: 3
