name: Build Openwrt kernel

on:
  workflow_dispatch:
    inputs:
      kernel_name:
        description: "Input kernel version"
        required: true
        default: ""
      kernel_auto:
        description: "Use last kernel?"
        required: false
        default: false
        type: boolean

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-22.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Set kernel repo
        run: |
          if [[ ${{ github.event.inputs.kernel_auto }} == false ]]; then
              KERNEL_VERSION=$(echo ${{ github.event.inputs.kernel_name }} | cut -d . -f 1-2)

      - name: Compile kernel use compile-auto
        uses: peter-evans/repository-dispatch@v2
        with:
          event-type: Build-Openwrt
          client-payload: '{"kernel_name": "${{ github.event.inputs.kernel_name }}", "kernel_repo_url": "${{ env.KERNEL_REPO }}"}'
