name: N1-ImmortalWrt-23.05

on:
  workflow_dispatch:

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-22.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Show system
      run: |
        echo -e "💬 Server information \n"
        echo -e "💻 Server running on Ubuntu: [ Release: $(cat /etc/os-release | grep VERSION_CODENAME | cut -d '=' -f2) / Host: $(arch) ] \n"
        echo -e "🧮 Server CPU configuration information: \n$(cat /proc/cpuinfo | grep name | cut -f2 -d: | uniq -c) \n"
        echo -e "💾 Server memory usage: \n$(free -h) \n"
        echo -e "🗃️ Server space usag: \n$(df -hT ${GITHUB_WORKSPACE}) \n"

    - name: Checkout
      uses: actions/checkout@v3

    - name: Initialization environment
      id: init
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        docker rmi $(docker images -q)
        [[ -n "${AGENT_TOOLSDIRECTORY}" ]] && sudo rm -rf "${AGENT_TOOLSDIRECTORY}"
        sudo rm -rf /usr/share/dotnet /etc/apt/sources.list.d /usr/local/lib/android 2>/dev/null
        sudo -E apt-get -y update
        sudo -E apt-get -y purge azure-cli* ghc* zulu* llvm* firefox google* dotnet* powershell openjdk* mongodb* moby* || true
        sudo -E apt-get -qq install $(cat depends)
        sudo -E systemctl daemon-reload
        #sudo -E apt-get -y full-upgrade
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean
        sudo timedatectl set-timezone "$TZ"
        echo "status=success" >> ${GITHUB_OUTPUT}

    - name: Prepare immortalwrt-23.05
      run: |
        sudo chown -R runner:runner /home/runner/work/build_openwrt
        cp -r scripts/immortalwrt-23.05/. ./
        /bin/bash 01_get_ready.sh
        echo "build_date=$(date +%Y.%m.%d)" >> ${GITHUB_ENV}

    - name: Prepare Package
      run: |
        cd openwrt
        cp -r ../scripts/immortalwrt-23.05/. ./
        /bin/bash 02_prepare_package.sh

    - name: Iptables
      run: |
        cd openwrt
        /bin/bash 03_ipt.sh

    - name: Load custom configuration
      run: |
        latest_release="$(curl -s https://github.com/immortalwrt/immortalwrt/tags | grep -Eo "v[0-9\.]+\-*r*c*[0-9]*.tar.gz" | sed -n '/[2-9][3-9]/p' | sed -n 1p | sed 's/.tar.gz//g' | sed 's/v//g')"
        cp -rf files openwrt/
        sed -i -e "s,DATE,${{ env.build_date }}," -e "s,VERSION,${latest_release}," ./init.sh
        mkdir -p openwrt/files/etc/uci-defaults
        cp -f ./init.sh openwrt/files/etc/uci-defaults/999-default-settings
        echo "latest_release=${latest_release}" >> ${GITHUB_ENV}

    - name: Make config
      run: |
        cd openwrt
        cp ../config/immortalwrt-23.05/config.seed .config
        make defconfig
        
    - name: Get Architecture
      working-directory: ${{ github.workspace }}/openwrt
      run: |
        TARGET_DEVICE_ARCH="$(grep "^CONFIG_TARGET_.*_.*=y$" ".config" | head -n 1 | sed 's/^CONFIG_TARGET_//g' | awk -F '_' '{print $1}')"
        echo "TARGET_DEVICE_ARCH=${TARGET_DEVICE_ARCH}" >>${GITHUB_ENV}

    - name: Cache
      uses: HiGarfield/cachewrtbuild@main
      with:
        mixkey: ${{ env.TARGET_DEVICE_ARCH }}
        prefix: ${{ github.workspace }}/openwrt

    - name: Download package
      id: package
      run: |
        cd openwrt
        make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    - name: Compile the firmware
      id: compile
      run: |
        cd openwrt
        echo -e "$(nproc) thread compile"
        make -j$(nproc) || make -j1 || make -j1 V=s
        echo "status=success" >> ${GITHUB_OUTPUT}

    - name: Package Openwrt
      if: steps.compile.outputs.status == 'success'
      uses: ffuqiangg/amlogic-s9xxx-openwrt@main
      with:
        openwrt_path: openwrt/bin/targets/*/*/*rootfs.tar.gz
        openwrt_board: s905d
        kernel_repo: ophub/kernel
        openwrt_kernel: 5.15.1
        kernel_usage: flippy
        auto_kernel: true
        image_name: N1-ImmortalWrt-${{ env.latest_release }}

    - name: Upload firmware to release
      uses: ncipollo/release-action@main
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        tag: ${{ env.build_date }}
        artifacts: |
          ${{ env.PACKAGED_OUTPUTPATH }}/N1-ImmortalWrt-*.zip

    - name: telegram notification
      run: |
        msg="
        ✅ *immortalwrt-${{ env.latest_release }}* 固件编译完成
        https://github.com/ffuqiangg/build\_openwrt/releases/tag/${{ env.build_date}}
        "
        curl "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage" -d "chat_id=${{ secrets.TELEGRAM_TO }}&text=${MSG}&parse_mode=MarkDown&disable_web_page_preview=true"
