name: Use release file to build

on:
  repository_dispatch:
    types:
      - Release-Build

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Package Armvirt as OpenWrt
        uses: ffuqiangg/openwrt_packit@master
        env:
          SCRIPT_REPO_URL: https://github.com/ffuqiangg/openwrt_packit
          OPENWRT_ARMVIRT: https://github.com/ffuqiangg/build_openwrt/releases/download/${{ github.event.client_payload.release_tag }}/openwrt-armvirt-64-default-rootfs.tar.gz 
          PACKAGE_SOC: s905d
          KERNEL_REPO_URL: ${{ github.event.client_payload.kernel_repo_url }}
          KERNEL_VERSION_NAME: ${{ github.event.client_payload.kernel_name }}
          KERNEL_AUTO_LATEST: ${{ github.event.client_payload.kernel_auto }}
          GZIP_IMGS: .7z
          SCRIPT_S905D: mk_lede_n1.sh
          OPENWRT_VER: ${{ github.event.client_payload.compile_date }}
          SFE_FLOW: 0
          ENABLE_WIFI_K504: 0
          ENABLE_WIFI_K510: 0
          DISTRIB_REVISION: ${{ github.event.client_payload.compile_date }} 

      - name: Upload firmware to release
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: ${{ github.event.client_payload.release_tag }}
          file: |
            ${{ env.PACKAGED_OUTPUTPATH }}/*.7z

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          retain_days: 1
          keep_minimum_runs: 3

